name: daps-project
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cython=3.2.0=py311hac7d6c3_0
  - icu=75.1=hfee45f7_0
  - libcxx=21.1.5=hf598326_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=h18782d2_2_cpython
  - python_abi=3.11=8_cp311
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_2
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h925e9cb_3
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - cbor2==5.7.1
      - certifi==2022.9.14
      - charset-normalizer==2.1.1
      - click==8.1.7
      - clip==1.0
      - contourpy==1.0.5
      - cycler==0.11.0
      - diffusers==0.32.2
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - filelock==3.14.0
      - fonttools==4.37.2
      - frozenlist==1.8.0
      - fsspec==2024.5.0
      - ftfy==6.3.1
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.74.0
      - grpclib==0.4.8
      - h2==4.3.0
      - hpack==4.1.0
      - huggingface-hub==0.29.3
      - hydra-core==1.3.2
      - hyperframe==6.1.0
      - idna==3.4
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - kiwisolver==1.4.4
      - kornia==0.7.3
      - kornia-rs==0.1.10
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - modal==1.2.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.1
      - numpy==1.24.4
      - omegaconf==2.3.0
      - packaging==21.3
      - pillow==10.3.0
      - piq==0.8.0
      - platformdirs==4.2.2
      - prettytable==3.10.0
      - propcache==0.4.1
      - protobuf==4.25.3
      - psutil==5.9.8
      - pygments==2.19.2
      - pyparsing==3.0.9
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytorch-lightning==1.0.8
      - pyyaml==6.0
      - regex==2024.11.6
      - requests==2.28.1
      - rich==14.2.0
      - safetensors==0.5.3
      - scipy==1.10.1
      - sentry-sdk==2.2.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - sigtools==4.0.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - sympy==1.12
      - synchronicity==0.10.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.20.3
      - toml==0.10.2
      - torch==2.3.1
      - torchaudio==2.3.1
      - torchdiffeq==0.2.5
      - torchvision==0.18.1
      - tqdm==4.64.1
      - transformers==4.46.3
      - typer==0.20.0
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.20240310
      - typing-extensions==4.15.0
      - urllib3==1.26.12
      - wandb==0.17.0
      - watchfiles==1.1.1
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - yarl==1.22.0
      - zipp==3.20.2
prefix: /opt/anaconda3/envs/daps-project
